services:
  - type: web
    name: viral-clip-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 600 --workers 1 --preload --max-requests 1 --max-requests-jitter 0 wsgi:app
    envVars:
      - key: VITE_GEMINI_API_KEY
        sync: false
      - key: UPLOAD_FOLDER
        value: uploads
      - key: OUTPUT_FOLDER
        value: viral_clips
    disk:
      name: video-storage
      mountPath: /opt/render/project
      sizeGB: 10




